name: build

on:
  pull_request:
    branches: 'master'
    paths:
      - '.github/workflows/build.yml'
      - 'app/**'
      - 'chocolatey/**'
      - 'data/**'
      - '*.go'
      - 'go.mod'
      - 'go.sum'
  push:
    branches: 'master'
    tags: '*.*.*'
    paths:
      - '.github/workflows/build.yml'
      - 'app/**'
      - 'chocolatey/**'
      - 'data/**'
      - '*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  release:
    runs-on: windows-latest
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=version::0.0.0
          fi
        shell: bash
      -
        name: Checkout
        uses: actions/checkout@v2.3.2
      -
        name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Mage build
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: build
      -
        name: Mage chocoPack
        uses: crazy-max/ghaction-mage@v1
        if: success()
        with:
          version: latest
          args: chocoPack
      -
        name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: WindowsSpyBlocker
          path: |
            bin/WindowsSpyBlocker.exe
            bin/windowsspyblocker.${{ steps.prepare.outputs.version }}.nupkg
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            bin/WindowsSpyBlocker.exe
            bin/windowsspyblocker.${{ steps.prepare.outputs.version }}.nupkg
          name: ${{ steps.prepare.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Mage chocoPush
        uses: crazy-max/ghaction-mage@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        with:
          version: latest
          args: chocoPush
